# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Validate Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.0
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [journey, accessibility]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.0
        cache: 'npm'
    - run: npm ci
    - run: |
        npm run dev &
        sleep 5 &&
        curl http://localhost:3000 -I
    - run: npm run test:${{matrix.test-type}}:cli
